version: '3.4'

services:

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"


  coin.api:
    container_name: coin.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
        
  ocelot.apigate:
    container_name: ocelot.apigate
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8020:80"
  
    
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    ports:
      - "8002:80"
    depends_on:
      - basketdb

