version: '3.4'

services:
    
  portainer:
    container_name: portainer
    restart: always
    ports:
       # - "8080:80"
      - "8080:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
 
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
       - "5672:5672"
       - "15672:15672" 

  
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  
  orderdb:
    container_name: orderdb
    environment:
      - SA_PASSWORD=amirB1379
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"

      ###############################

  coin.api:
    container_name: coin.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
        
  ocelot.apigate:
    container_name: ocelot.apigate
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8020:80"
  
    
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8002:80"
    depends_on:
      - basketdb
      - rabbitmq


  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb,1433;TrustServerCertificate=True;Database=Ordering.API;User ID=sa;Password=amirB1379"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8003:80"


