version: '3.4'

services:
  
  #  portainer:
  #    image: portainer/portainer
  
  pgadmin:
    image: dpage/pgadmin4
    
  rabbitmq:
    image: rabbitmq:3-management-alpine


  basketdb:
    image: redis
    ports:
      - "6379:6379"
  
  
  orderdb:
    image: mcr.microsoft.com/mssql/server:latest
  
  
  # identitydb:
  #   image: mcr.microsoft.com/mssql/server:latest
   
  identitydb:
    image: postgres


  walletdb:
    image: mongo



  ###############################     
  coin.api:
    image: coin.api
    build:
      context: .
      dockerfile: Coin.API/Dockerfile


  ocelot.Gateways:
    image: ocelot.apigate
    build:
      context: .
      dockerfile: Ocelot.ApiGate/Dockerfile


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.API/Dockerfile


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    environment:
      TZ: Asia/Tehran
    build:
      context: .
      dockerfile: Oedering/Ordering.API/Dockerfile


  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    environment:
      TZ: Asia/Tehran
    build:
      context: .
      dockerfile: Identity.API/Dockerfile


  wallet.api:
    image: ${DOCKER_REGISTRY-}walletapi
    build:
      context: .
      dockerfile: Wallet.API/Dockerfile


volumes:
  portainer_data:
  mongo_data:
  postgres_data:
  pgadmin_data:


