version: '3.4'

services:

  portainer:
    image: portainer/portainer


  rabbitmq:
    image: rabbitmq:3-management-alpine


  basketdb:
     image: redis
     ports:
      - "6379:6379"
    
  orderdb:
     image: mcr.microsoft.com/mssql/server:latest

  ###############################     
  coin.api:
    image: coin.api
    build:
      context: .
      dockerfile: Coin.API/Dockerfile

  ocelot.apigate:
    image: ocelot.apigate
    build:
      context: .
      dockerfile: Ocelot.ApiGate/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.API/Dockerfile


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Oedering/Ordering.API/Dockerfile


volumes:
    portainer_data: